### ISSUE TITLE
sklearn的那一篇不写了?

### ISSUE THREAD

**Issue by WangZhonglei** [NLP-LOVE/ML-NLP#1]
感觉很基本啊,模块的算法当然不止这些,整理一下还是不错的

**Comment by NLP-LOVE** [comment]
sklearn知识点都比较散，我认为看官网文档或中文文档就足够了。
如果你想要整理这一块，到时可以放进来。

**Comment by WangZhonglei** [comment]
目前还在找工作.没时间
